# Generated by Django 4.1.1 on 2024-10-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EebRecord',
            fields=[
                ('pqid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=20)),
                ('source_library', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=5000)),
                ('displaydate', models.CharField(max_length=50)),
                ('startdate', models.CharField(max_length=8)),
                ('enddate', models.CharField(blank=True, max_length=8, null=True)),
                ('imprint', models.CharField(blank=True, max_length=500, null=True)),
                ('ustc_bibliographic_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('shelfmark', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('pagination', models.CharField(blank=True, max_length=255, null=True)),
                ('source_collection', models.CharField(blank=True, max_length=255, null=True)),
                ('ustc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ustc_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'eeb_record',
                'managed': False,
            },
        ),
    ]
